### ISSUE TITLE
Clicking on some files crashes the  UI with an "Ooops!"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#111] opened 2023-09-21 09:44 UTC
Whenever I click on some files, the UI crashes. I'm not sure what is in common with the files yet.

I've seen it happen with JSON files, txt files, JPGs, etc.

**Comment by garrett** [comment] 2023-09-21 09:46
This is the stacktrace:

```js
Uncaught RangeError: date value is not finite in DateTimeFormat.format()
    dateTime timeformat.js:31
    getDescriptionListItems sidebar.jsx:71
    SidebarPanelDetails sidebar.jsx:188
    React 16
    handleClick app.jsx:531
    onClick app.jsx:555
    React 23
    <anonymous> index.js:37
    EventListener.handleEvent* index.js:36
    <anonymous> index.js:47845
timeformat.js:31:84
Uncaught RangeError: date value is not finite in DateTimeFormat.format()
    dateTime timeformat.js:31
    getDescriptionListItems sidebar.jsx:71
    SidebarPanelDetails sidebar.jsx:188
    React 17
    handleClick app.jsx:531
    onClick app.jsx:555
    React 23
    <anonymous> index.js:37
    EventListener.handleEvent* index.js:36
    <anonymous> index.js:47845
timeformat.js:31:84
The above error occurred in the <SidebarPanelDetails> component:

SidebarPanelDetails@https://localhost:9090/cockpit/@localhost/navigator/index.js:47021:29
div
SidebarPanel@https://localhost:9090/cockpit/@localhost/navigator/index.js:42638:92
div
div
Sidebar@https://localhost:9090/cockpit/@localhost/navigator/index.js:42606:109
section
PageSection@https://localhost:9090/cockpit/@localhost/navigator/index.js:42585:289
main
div
Page@https://localhost:9090/cockpit/@localhost/navigator/index.js:42337:7
Application@https://localhost:9090/cockpit/@localhost/navigator/index.js:47344:35
WithDialogs@https://localhost:9090/cockpit/@localhost/navigator/index.js:31522:21

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. react-dom.development.js:18687:14
Uncaught RangeError: date value is not finite in DateTimeFormat.format()
    dateTime timeformat.js:31
    getDescriptionListItems sidebar.jsx:71
    SidebarPanelDetails sidebar.jsx:188
    React 14
    handleClick app.jsx:531
    onClick app.jsx:555
    React 23
    <anonymous> index.js:37
    EventListener.handleEvent* index.js:36
    <anonymous> index.js:47845
timeformat.js:31:84
```

**Comment by subhoghoshX** [comment] 2023-09-21 14:08
I can confirm. Initially there's a list of errors in the console (before clicking any file):

![image](https://github.com/KKoukiou/cockpit-navigator/assets/108616679/68f3223a-327b-408e-9526-91891cc01604)

Clicking on any files or directories it goes "Ooops!":

![image](https://github.com/KKoukiou/cockpit-navigator/assets/108616679/4ac5c969-11b4-4fb7-87ed-e45b3dd2c65b)

**Comment by jelly** [comment] 2023-10-05 15:03
Yup, this is a race condition.

```
diff --git a/src/sidebar.jsx b/src/sidebar.jsx
index 0b59576..87e01de 100644
--- a/src/sidebar.jsx
+++ b/src/sidebar.jsx
@@ -60,10 +60,15 @@ import { permissions } from "./common.js";
 const _ = cockpit.gettext;

 const getDescriptionListItems = selected => {
+    console.log("selected", selected);
     const getPermissions = (str) => {
         return permissions.find(e => e.value === str).label;
     };

+    if (!selected.modified) {
+        return [];
+    }
+
```


And
```
Uncaught TypeError: selected.permissions is undefined
```

**Comment by jelly** [comment] 2023-10-05 15:13
This seems to be mostly right clicking on directories for me which triggers it:
```
Object { event: "present", path: "proc-macro-error-a708da44cfa50456", type: "directory", name: "proc-macro-error-a708da44cfa50456", isHidden: false }
​
event: "present"
​
isHidden: false
​
name: "proc-macro-error-a708da44cfa50456"
​
path: "proc-macro-error-a708da44cfa50456"
​
type: "directory"
​
<prototype>: Object { … }
[fileActions.jsx:391:12](https://t14s:9090/cockpit/@localhost/src/fileActions.jsx)
Uncaught TypeError: selected.permissions is undefined
    EditPermissionsModal fileActions.jsx:395
```

**Comment by jelly** [comment] 2023-10-06 11:58
I think in essence there are two problems, one is that loading all files sometimes fails:

```
Adding file failed 
Object { event: "present", path: ".nuget", type: "directory", name: ".nuget", isHidden: true }
 
Object { problem: "internal-error", exit_status: null, exit_signal: null, message: "Internal error", toString: toString()
 }
[fileActions.jsx:626:30](https://t14s:9090/cockpit/@localhost/src/fileActions.jsx)
```

```
/home/jelle 
Array [ "home", "jelle" ]
 home/jelle/ [app.jsx:75:12](http://localhost:9999/cockpit/@localhost/src/app.jsx)
/home/jelle 
Array [ "home", "jelle" ]
 home/jelle/
 ```
 
 No idea why we do this path shuffling around. Especially creating the currentDir from the broken apart path and then not adding a trailing / does not seem to make much sense.

**Comment by jelly** [comment] 2023-10-06 12:59
Unrelated this is another issue:
```
Oct 06 12:55:33 fedora-38-127-0-0-2-2201 cockpit-ws[3482]: cockpit.protocol-DEBUG: channel control received {'payload': 'stream', 'spawn': ['file', '--brief', 'usr/sbin/undefined'], 'superuser': 'try', 'error': 'message', 'command': 'open', 'channel': '1:1!574', 'host': 'localhost', 'flow-control': True, 'group': 'cockpit1:localhost/navigato>
```

How we end up with `/usr/sbin/undefined` I'm not sure.

**Comment by jelly** [comment] 2024-01-22 14:41
Let's recheck this with `fsinfo` support

**Comment by jelly** [comment] 2024-04-09 12:16
We have merged fsinfo support and I haven't seen this pop up.

**Closed by jelly** 2024-04-09 12:16 UTC
Labels: bug
