### ISSUE TITLE
ARM CPU Support

### ISSUE THREAD

**Issue by Patrick-1-1-1-PH** [cockpit-project/cockpit-files#803] opened 2024-10-24 06:13 UTC
Compiling the source for arm boards will not work. This ticket humbly requests support for it. Thank you!

Why do arm boards need `cockpit-files`?
The same reason other people need them to. They need to access the files.
For me, I need to edit the php-html-css-js files in /var/www/* without using samba when I am outside my home.
I trust cockpit, i think it is more secure than ssh when it is exposed to the internet.

**Comment by martinpitt** [comment] 2024-10-24 07:04
Hello @Patrick-1-1-1-PH ! This is a duplicate of #609. There are two workarounds:
```
rm -r node_modules
npm install
./build.js
```

or build on x86 and `make install DESTDIR=/tmp/install` and then transfer /tmp/install/ to the ARM machine (the result is platform independent)

**Closed by martinpitt** 2024-10-24 07:04 UTC
